-- CreateTable
CREATE TABLE "Junk" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "code" STRING NOT NULL,
    "article" STRING NOT NULL,
    "name" STRING NOT NULL,

    CONSTRAINT "Junk_pkey" PRIMARY KEY ("id")
);
