/*
  Warnings:

  - You are about to drop the `Junk` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropTable
DROP TABLE "Junk";

-- CreateTable
CREATE TABLE "junk" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "foo" STRING NOT NULL,
    "bar" STRING NOT NULL,
    "baz" STRING NOT NULL,
    "bim" STRING NOT NULL,

    CONSTRAINT "junk_pkey" PRIMARY KEY ("id")
);
